version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lodash
    versions:
    - 4.17.20
